### ISSUE TITLE
What does "Move the camera back x units" mean?

### ISSUE THREAD

**Issue by Madoshakalaka** [kotauskas/fpvsetup#1]
First of all thanks! I used to have serious motion sickness while playing Minecraft. Sometimes I feel like throwing up after 20 minutes of playing. I just tried this tool and felt great.

![image](https://user-images.githubusercontent.com/44753941/160883674-96c39b64-afb4-4ed5-b240-28de1f8dc0f4.png)

Question though, what does  "Move the camera back" mean?

**Comment by Madoshakalaka** [comment]
Sorry for the accidental "bug" label, I don't think I have permission to edit it.

**Comment by kotauskas** [comment]
The essence of the portal-like mode is that the tool is trying to pick two parameters for the camera such that your monitor would feel like a portal into the 3D world that's being rendered, where the eyes of the player character act as the portal surface. This would give you fully accurate scale perception and better immersion, as long as the game allows you to set those parameters up correctly.

The first parameter is the FoV (*horizontal*, not vertical), it's pretty obvious to set up in Minecraft, though I've heard that the slider sets vertical FoV instead of the horizontal one, so you'd have to convert it by multiplying it by your aspect ratio, typically 1.777778 for a 16:9 monitor.

The second parameter, the less obvious one, is the camera pushback distance, the one you're asking about. In order for the effect to be complete, the game is supposed to move the camera back by that many units, and maybe also move the near clipping plane forward by just as many units to prevent things from getting in the way (or not — maybe you want your view to be obstructed by things that are supposed to be in the way). This mode has issues when you're particularly far away from the screen, since the bigger the pushback, the bigger the third-person-esque orbiting effect and the chance that something will get in the way.

From what I know, Minecraft doesn't actually have a way to set that up. Your camera is locked to your eyes, and when it's not, you're playing in a smart dynamic third-person mode that chooses the distance and near clipping plane as it sees fit.

Your two choices are to use the FoV as-is, converting it into a vertical FoV as I described above, or to use the Focused tab to specify a distance in in-game units at which you want accurate scale perception.

**Comment by Madoshakalaka** [comment]
Thanks! That answers it!
